KaniTietoKantaMVC/Models/Astutukset.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KaniTietoKantaMVC.Models
{
    public partial class Astutukset
    {
        public int AstutusId { get; set; }
        [Required(ErrorMessage = "Syötä astutuspäivä")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = false)]
        public DateTime? Astutuspäivä { get; set; }

        public int? IsäId { get; set; }

        [Required(ErrorMessage = "Syötä isän kutsumanimi")]
        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string IsäKnimi { get; set; }

        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string IsäVnimi { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = false)]
        public DateTime? IsäSyntymäpv { get; set; }

        [StringLength(150, ErrorMessage = "Maksimipituus 150 merkkiä")]
        public string IsäVäri { get; set; }

        [Required(ErrorMessage = "Syötä isän rotu")]
        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string IsäRotu { get; set; }

        public int? EmäId { get; set; }

        [Required(ErrorMessage = "Syötä emän kutsumanimi")]
        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string EmäKnimi { get; set; }

        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string EmäVnimi { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = false)]
        public DateTime? EmäSyntymäpv { get; set; }

        [StringLength(150, ErrorMessage = "Maksimipituus 150 merkkiä")]
        public string EmäVäri { get; set; }

        [Required(ErrorMessage = "Syötä emän rotu")]
        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string EmäRotu { get; set; }

        [StringLength(500, ErrorMessage = "Maksimipituus 500 merkkiä")]
        public string Lisätietoja { get; set; }

        public string Email { get; set; }

        public virtual Kani Emä { get; set; }
        public virtual Kani Isä { get; set; }
    }
}

KaniTietoKantaMVC/Models/Poikueet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KaniTietoKantaMVC.Models
{
    public partial class Poikueet
    {
        public Poikueet()
        {
            Kani = new HashSet<Kani>();
        }

        public int PoikueId { get; set; }
        public int? EmäId { get; set; }
        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string EmäVnimi { get; set; }
        [Required(ErrorMessage = "Syötä emän kutsumanimi")]
        [StringLength(50, ErrorMessage = "Maksimipituus 50 merkkiä")]
        public string EmäKnimi { get; set; }
        public string EmäVk { get; set; }
        public int? IsäId { get; set; }
        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string IsäVnimi { get; set; }
        [Required(ErrorMessage = "Syötä isän kutsumanimi")]
        [StringLength(50, ErrorMessage = "Maksimipituus 50 merkkiä")]
        public string IsäKnimi { get; set; }
        public string IsäVk { get; set; }
        public int? Poikaslkm { get; set; }

        [Required(ErrorMessage = "Syötä poikueen syntymäpäivä")]
        [DataType(DataType.Date)]
        public DateTime? Syntymäpv { get; set; }

        [Required(ErrorMessage = "Syötä poikueen rotu")]
        [StringLength(100, ErrorMessage = "Maksimipituus 100 merkkiä")]
        public string Rotu { get; set; }

        [StringLength(300, ErrorMessage = "Maksimipituus 300 merkkiä")]
        public string Tietoja { get; set; }

        public string Email { get; set; }

        public virtual Kani Emä { get; set; }
        public virtual Kani Isä { get; set; }
        public virtual ICollection<Kani> Kani { get; set; }
    }
}

KaniTietoKantaMVC/Controllers/KaniDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using KaniTietoKantaMVC.Models;
using System.Net.Http.Headers;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using KaniTietoKantaMVC.Extensions;
using KaniTietoKantaMVC.ViewModels;
using System.Security.Claims;
//using System.Text.Json;

namespace KaniTietoKantaMVC.Controllers
{
    public class KaniDBController : Controller
    {
        public static string errormsg;
        public static bool astutusvalittu = false;
        public static int astutusid = 0;

        public string UserEmail()
        {
            return User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
        }
        //public List<Kani> HaeKanitEmaililla(List<Kani> kaikki)
        //{
        //    kaikki = (from k in kaikki
        //              where k.Email == UserEmail()
        //              select k).ToList();

        //    return kaikki;
        //}

        //public List<Poikueet> HaePoikueetEmaililla(List<Poikueet> kaikki)
        //{
        //    kaikki = (from k in kaikki
        //              where k.Email == UserEmail()
        //              select k).ToList();

        //    return kaikki;
        //}

        // GET: KaniDB/Error

        public ActionResult Error()
        {
            ViewBag.Message = errormsg;

            return View();
        }

        // GET: KaniDB
        public ActionResult Index()
        {
            return View();
        }


        #region perus tietohaku

        // GET: KaniDB/Sukupuu/5
        public ActionResult Sukupuu(int kaniid = 0)
        {
            if (!User.Identity.IsAuthenticated)
            {
                errormsg = "Kirjaudu ensin sisään käyttääksesi tätä ominaisuutta.";
                return RedirectToAction("Error");
            }


            List<Kani> kaikkikanit = DataHelper.HaeKaikkiKanit(UserEmail());
            List<Poikueet> kaikkipoikueet = DataHelper.HaeKaikkiPoikueet(UserEmail());

            ViewBag.Kaikkikanit = kaikkikanit;

            if (kaniid == 0)
            {
                ViewBag.Haku = false;
                return View();
            }
            ViewBag.Haku = true;


            Kani haettu = DataHelper.HaeKaniIdllä(kaniid);

            if (haettu == null || haettu.Email != UserEmail())
            {
                errormsg = "Tätä kania ei löydy tietokannastasi.";
                return RedirectToAction("Error");
            }

            //Kani haettu = (from k in kaikkikanit
            //               where k.KaniId == id
            //               select k).FirstOrDefault();



            ViewBag.Haettu = haettu;

            EmäIsä e = new EmäIsä();
            EmäIsä ee = new EmäIsä();
            EmäIsä ei = new EmäIsä();
            EmäIsä i = new EmäIsä();
            EmäIsä ie = new EmäIsä();
            EmäIsä ii = new EmäIsä();

            if (haettu.PoikueenId != null)
            {
                Poikueet eka = new Poikueet();

                eka = (from ekapoikue in kaikkipoikueet
                       where ekapoikue.PoikueId == haettu.PoikueenId
                       select ekapoikue).FirstOrDefault();

                //haetaan emä

                if (eka.EmäId != null)
                {
                    e.KaniId = eka.EmäId;
                }
                if (eka.EmäVnimi != null)
                {
                    e.Vnimi = eka.EmäVnimi;
                }
                e.Knimi = eka.EmäKnimi;

                //haetaan emän kanitiedot, jos löytyy
                if (e.KaniId != null)
                {
                    Kani eKani = (from k in kaikkikanit
                                   where k.KaniId == e.KaniId
                                   select k).FirstOrDefault();

                    //jos emällä on poikue liitettynä, haetaan sen tiedot
                    if (eKani != null && eKani.PoikueenId != null)
                    {
                        ViewBag.EmänPoikue = true;

                        Poikueet emänpoikue = (from p in kaikkipoikueet
                                               where p.PoikueId == eKani.PoikueenId
                                               select p).FirstOrDefault();

                        //haetaan poikueest emän emän tiedot

                        if (emänpoikue.EmäId != null)
                        {
                            ee.KaniId = emänpoikue.EmäId;
                        }
                        if (emänpoikue.EmäVnimi != null)
                        {
                            ee.Vnimi = emänpoikue.EmäVnimi;
                        }
                        ee.Knimi = emänpoikue.EmäKnimi;

                        //haetaan poikueesta emän isän tiedot

                        if (emänpoikue.IsäId != null)
                        {
                            ei.KaniId = emänpoikue.IsäId;
                        }
                        if (emänpoikue.IsäVnimi != null)
                        {
                            ei.Vnimi = emänpoikue.IsäVnimi;
                        }
                        ei.Knimi = emänpoikue.IsäKnimi;
                    }
                    else
                    {
                        ee.Knimi = eKani.EmänNimi;
                        ei.Knimi = eKani.IsänNimi;
                        ViewBag.EmänPoikue = false;
                    }
                }

                //haetaan isä
                if (eka.IsäId != null)
                {
                    i.KaniId = eka.IsäId;
                }
                if (eka.IsäVnimi != null)
                {
                    i.Vnimi = eka.IsäVnimi;
                }
                i.Knimi = eka.IsäKnimi;

                //haetaan isän kanitiedot, jos löytyy
                if (i.KaniId != null)
                {
                    Kani iKani = (from k in kaikkikanit
                                   where k.KaniId == i.KaniId
                                   select k).FirstOrDefault();

                    //jos isällä on poikue liitettynä, haetaan sen tiedot
                    if (iKani != null && iKani.PoikueenId != null)
                    {
                        Poikueet isänpoikue = (from p in kaikkipoikueet
                                               where p.PoikueId == iKani.PoikueenId
                                               select p).FirstOrDefault();

                        //haetaan poikueest isän emän tiedot

                        if (isänpoikue.EmäId != null)
                        {
                            ie.KaniId = isänpoikue.EmäId;
                        }
                        if (isänpoikue.EmäVnimi != null)
                        {
                            ie.Vnimi = isänpoikue.EmäVnimi;
                        }
                        ie.Knimi = isänpoikue.EmäKnimi;

                        //haetaan poikueesta isän isän tiedot

                        if (isänpoikue.IsäId != null)
                        {
                            ii.KaniId = isänpoikue.IsäId;
                        }
                        if (isänpoikue.IsäVnimi != null)
                        {
                            ii.Vnimi = isänpoikue.IsäVnimi;
                        }
                        ii.Knimi = isänpoikue.IsäKnimi;
                    }
                    else
                    {
                        ie.Knimi = iKani.EmänNimi;
                        ii.Knimi = iKani.IsänNimi;
                        ViewBag.IsänPoikue = false;
                    }

                }
            }
            else
            {
                e.Knimi = haettu.EmänNimi;
                i.Knimi = haettu.IsänNimi;
                ViewBag.EkanPoikue = false;
                ViewBag.EmänPoikue = false;
                ViewBag.IsänPoikue = false;
            }


            ViewBag.E = e;
            ViewBag.Ee = ee;
            ViewBag.Ei = ei;
            ViewBag.I = i;
            ViewBag.Ie = ie;
            ViewBag.Ii = ii;

            return View();
        }

        // GET: KaniDB/Rokotukset
        public ActionResult Rokotukset()
        {
            List<Kani> kaikki = DataHelper.HaeKaikkiKanit(UserEmail());

            List<Kani> voimassa = (from k in kaikki
                                   where k.Kuollut == false &&
                                   k.Myyty == false &&
                                   (DateTime.Now.Date - Convert.ToDateTime(k.Rokotuspv)).Days < 365
                                   orderby k.Rokotuspv ascending
                                   select k).ToList();

            List<Kani> vanhentuneet = (from k in kaikki
                                       where k.Rokotuspv != null &&
                                       k.Kuollut == false &&
                                       k.Myyty == false &&
                                       (DateTime.Now.Date - Convert.ToDateTime(k.Rokotuspv)).Days > 365
                                       orderby k.Rokotuspv ascending
                                       select k).ToList();

            List<Kani> eirokotettu = (from k in kaikki
                                      where k.Rokotettu == false
                                      && k.Kuollut == false &&
                                      k.Myyty == false
                                      orderby k.Syntymäpäivä descending
                                      select k).ToList();

            if (voimassa.Count != 0)
            {
                ViewBag.Voimassa = voimassa;
            }
            if (vanhentuneet.Count != 0)
            {
                ViewBag.Vanhentuneet = vanhentuneet;
            }
            if (eirokotettu.Count != 0)
            {
                ViewBag.EiRokotettu = eirokotettu;
            }

            return View();
        }

        // GET: KaniDB/Details/5

KaniTietoKantaMVC/Views/KaniDB/Astutukset.cshtml
@model IEnumerable<KaniTietoKantaMVC.Models.Astutukset>

@{
    ViewData["Title"] = "Astutukset";
}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h1 class="display-4">Astutukset</h1>
        </div>
        <div class="col-md-3">
            <p>
                <a asp-action="UusiAstutus" class="btn btn-secondary btn-lg">Lisää uusi</a>
            </p>
        </div>
    </div>
</div>
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Astutuspäivä)
            </th>
            <th>
                Isä
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.IsäSyntymäpv)
                </th>*@
            <th scope="col" class="d-none d-lg-table-cell">
                Isän väri
            </th>
            <th scope="col" class="d-none d-md-table-cell">
                Isän rotu
            </th>
            <th>
                Emä
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.EmäSyntymäpv)
                </th>*@
            <th scope="col" class="d-none d-lg-table-cell">
               Emän väri
            </th>
            <th scope="col" class="d-none d-md-table-cell">
                Emän rotu
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="location.href = '@(Url.Action("Astutuksentiedot", "KaniDB", new { id = item.AstutusId }))'">
                @*<td>
                        @Html.DisplayFor(modelItem => item.AstutusId)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Astutuspäivä, "{0:dd.MM.yyyy}")
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.IsäId)
                    </td>*@
                <td>
                    @if (item.IsäVnimi != null)
                    {
                        @Html.DisplayFor(modelItem => item.IsäVnimi)
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.IsäKnimi)
                    }
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.IsäSyntymäpv)
                    </td>*@
                <td scope="col" class="d-none d-lg-table-cell">
                    @Html.DisplayFor(modelItem => item.IsäVäri)
                </td>
                <td scope="col" class="d-none d-md-table-cell">
                    @Html.DisplayFor(modelItem => item.IsäRotu)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.EmäId)
                    </td>*@
            <td>
                @if (item.EmäVnimi != null)
                {
                    @Html.DisplayFor(modelItem => item.EmäVnimi)
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.EmäKnimi)
                }
            </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.EmäSyntymäpv)
                    </td>*@
                <td scope="col" class="d-none d-lg-table-cell">
                    @Html.DisplayFor(modelItem => item.EmäVäri)
                </td>
                <td scope="col" class="d-none d-md-table-cell">
                    @Html.DisplayFor(modelItem => item.EmäRotu)
                </td>
            </tr>
        }
    </tbody>
</table>

KaniTietoKantaMVC/Views/KaniDB/Kaikki.cshtml
@model IEnumerable<KaniTietoKantaMVC.Models.Kani>

@{
    ViewData["Title"] = "Kaikki";
}

@*<script>
        $(document).on("click", ".ClickToEdit", function () {
        var custID = $(this).data("KaniId");
        window.opener.location.href("/Edit/Edit?id=" + KaniId);
    });
    </script>*@

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h1 class="display-4">Kanit</h1>
        </div>
        <div class="col-md-3">
            <p>
                <a asp-action="UusiKani" class="btn btn-secondary btn-lg">Lisää kani</a>
            </p>
        </div>
    </div>
</div>
<br />
<form class="form-inline" method="get" action="@Url.Action("Kaikki", "KaniDB")">
    <div class="form-group mx-sm-3 mb-2">
        <input type="text" class="form-control" name="hakusana" id="hakusana" value=@ViewBag.HakuSana>
    </div>
    <div class="form-group mx-sm-3 mb-2">
        <div class="form-check form-check-inline">
            <input type="checkbox" class="form-check-input" name="kuolleet" id="kuolleet" value="true" @(ViewBag.Kuolleet == true ? "checked" : "unchecked")>
            <label class="form-check-label" for="kuolleet">Näytä kuolleet</label>
        </div>
        <div class="form-check form-check-inline">
            <input type="checkbox" class="form-check-input" name="myydyt" id="myydyt" value="true" @(ViewBag.Myydyt == true ? "checked" : "unchecked")>
            <label class="form-check-label" for="myydyt">Näytä myydyt</label>
        </div>
    </div>
    <button type="submit">Hae</button>
</form>
<br />

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Virallinen nimi", "Kaikki", new { järjestys = ViewBag.VNimiJärjestys, hakusana = ViewBag.HakuSana, kuolleet = ViewBag.Kuolleet, myydyt = ViewBag.Myydyt})
            </th>
            <th scope="col" class="d-none d-lg-table-cell">
                @Html.ActionLink("Kutsumanimi", "Kaikki", new { järjestys = ViewBag.KNimiJärjestys, hakusana = ViewBag.HakuSana, kuolleet = ViewBag.Kuolleet, myydyt = ViewBag.Myydyt})
            </th>
            <th>
                @Html.ActionLink("Rotu", "Kaikki", new { järjestys = ViewBag.RotuJärjestys, hakusana = ViewBag.HakuSana, kuolleet = ViewBag.Kuolleet, myydyt = ViewBag.Myydyt})
            </th>
            <th scope="col" class="d-none d-sm-table-cell">
                @Html.ActionLink("Väri", "Kaikki", new { järjestys = ViewBag.VäriJärjestys, hakusana = ViewBag.HakuSana, kuolleet = ViewBag.Kuolleet, myydyt = ViewBag.Myydyt})
            </th>
            <th scope="col" class="d-none d-md-table-cell">
                @Html.ActionLink("Sukupuoli", "Kaikki", new { järjestys = ViewBag.SkpJärjestys, hakusana = ViewBag.HakuSana, kuolleet = ViewBag.Kuolleet, myydyt = ViewBag.Myydyt})
            </th>
            <th>
                @Html.ActionLink("Syntymäpäivä", "Kaikki", new { järjestys = ViewBag.SpvJärjestys, hakusana = ViewBag.HakuSana, kuolleet = ViewBag.Kuolleet, myydyt = ViewBag.Myydyt})
            </th>
            @if (ViewBag.Kuolleet == true)
            {
            <th scope="col" class="d-none d-lg-table-cell">
                @Html.ActionLink("Kuolinpäivä", "Kaikki", new { järjestys = ViewBag.KpvJärjestys, hakusana = ViewBag.HakuSana, kuolleet = ViewBag.Kuolleet, myydyt = ViewBag.Myydyt})
            </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr onclick="location.href = '@(Url.Action("Details", "KaniDB", new { id = item.KaniId }))'">
            <td>
                @Html.DisplayFor(modelItem => item.Nimi)
            </td>
            <td scope="col" class="d-none d-lg-table-cell">
                @Html.DisplayFor(modelItem => item.Kutsumanimi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rotu)
            </td>
            <td scope="col" class="d-none d-sm-table-cell">
                @Html.DisplayFor(modelItem => item.Väri)
            </td>
            <td scope="col" class="d-none d-md-table-cell">
                @Html.DisplayFor(modelItem => item.Sukupuoli)
            </td>
            <td>
                @Html.ValueFor(modelItem => item.Syntymäpäivä, "{0:dd.MM.yyyy}")
            </td>
            @if (ViewBag.Kuolleet == true)
                {
            <td scope="col" class="d-none d-lg-table-cell">
                @Html.ValueFor(modelItem => item.Kuolinpäivä, "{0:dd.MM.yyyy}")
            </td>
                }
        </tr>
        }
    </tbody>
</table>
<p>
    Sivunumero:
    @for (int i = 1; i <= ViewBag.Sivumäärä; i++)
    {
    @Html.ActionLink(i.ToString(), "Kaikki", new { järjestys = ViewBag.NykJärjestys, nykhaku = ViewBag.HakuSana, kuolleet = ViewBag.Kuolleet, myydyt = ViewBag.Myydyt, sivunro = i - 1 })
    <text> </text>
    }
</p>

KaniTietoKantaMVC/Views/KaniDB/Poikueet.cshtml
@model IEnumerable<KaniTietoKantaMVC.Models.Poikueet>

@{
    ViewData["Title"] = "Poikueet";
}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h1 class="display-4">Poikueet</h1>
        </div>
        <div class="col-md-3">
            <p>
                <a asp-action="UusiPoikue" class="btn btn-secondary btn-lg">Lisää poikue</a>
            </p>
        </div>
    </div>
</div>
<br />
<form class="form-inline" method="get" action="@Url.Action("Poikueet", "KaniDB")">
    <div class="form-group mx-sm-3 mb-2">
        <input type="text" class="form-control" name="hakusana" id="hakusana" value=@ViewBag.HakuSana>
    </div>
    <button type="submit">Hae</button>
</form>
<br />

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Syntymäpäivä", "Poikueet", new { järjestys = ViewBag.SpvJärjestys, hakusana = ViewBag.HakuSana})
            </th>
            <th scope="col" class="d-none d-md-table-cell">
                @Html.ActionLink("Rotu", "Poikueet", new { järjestys = ViewBag.RotuJärjestys, hakusana = ViewBag.HakuSana})
            </th>
            <th scope="col" class="d-none d-md-table-cell">
                @Html.ActionLink("Poikasia", "Poikueet", new { järjestys = ViewBag.LkmJärjestys, hakusana = ViewBag.HakuSana})
            </th>
            <th>
                @Html.ActionLink("Emä", "Poikueet", new { järjestys = ViewBag.ENimiJärjestys, hakusana = ViewBag.HakuSana})
            </th>
            <th>
                @Html.ActionLink("Isä", "Poikueet", new { järjestys = ViewBag.INimiJärjestys, hakusana = ViewBag.HakuSana})
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr onclick="location.href = '@(Url.Action("Poikuetiedot", "KaniDB", new { id = item.PoikueId }))'">
            <td>
                @Html.ValueFor(modelItem => item.Syntymäpv, "{0:dd.MM.yyyy}")
            </td>
            <td scope="col" class="d-none d-md-table-cell">
                @Html.DisplayFor(modelItem => item.Rotu)
            </td>
            <td scope="col" class="d-none d-md-table-cell">
                @Html.DisplayFor(modelItem => item.Poikaslkm)
            </td>
            <td>
                @if (item.EmäVnimi != null)
                {
                    @Html.DisplayFor(modelItem => item.EmäVnimi)
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.EmäKnimi)
                }
            </td>
            <td>
                @if (item.IsäVnimi != null)
                {
                    @Html.DisplayFor(modelItem => item.IsäVnimi)
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.IsäKnimi)
                }
            </td>
        </tr>
}
    </tbody>
</table>

<p>
    Sivunumero:
    @for (int i = 1; i <= ViewBag.Sivumäärä; i++)
        {
    @Html.ActionLink(i.ToString(), "Poikueet", new { järjestys = ViewBag.NykJärjestys, nykhaku=ViewBag.HakuSana, sivunro = i - 1})
    <text> </text>
        }
</p>

KaniTietoKantaMVC/Views/KaniDB/Rokotukset.cshtml
@model IEnumerable<KaniTietoKantaMVC.Models.Kani>

@{
    ViewData["Title"] = "Rokotukset";
}

<h1 class="display-4">Rokotukset</h1>


@if (ViewBag.Voimassa != null)
{
    <dl class="row">
        <dt class="col-sm-2">
            Rokotettu
        </dt>
        <dd class="col-sm-10">
            <table class="table-sm table-hover">
                <thead>
                    <tr>
                        <th>
                            Nimi
                        </th>
                        <th>
                            Rokotettu
                        </th>
                        <th>
                            Syntymäpäivä
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in ViewBag.Voimassa)
                    {
                        <tr onclick="location.href = '@(Url.Action("Details", "KaniDB", new { id = item.KaniId }))'">
                            <td>
                                @item.Nimi "@item.Kutsumanimi"
                            </td>
                            <td>
                                @item.Rokotuspv.ToShortDateString()
                            </td>
                            <td>
                                @item.Syntymäpäivä.ToShortDateString()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>
    </dl>
}
@if (ViewBag.Vanhentuneet != null)
{
    <dl class="row">
        <dt class="col-sm-2">
            Vanhentuneet rokotukset
        </dt>
        <dd class="col-sm-10">
            <table class="table-sm table-hover">
                <thead>
                    <tr>
                        <th>
                            Nimi
                        </th>
                        <th>
                            Rokotettu
                        </th>
                        <th>
                            Syntymäpäivä
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.Vanhentuneet)
                    {
                        <tr onclick="location.href = '@(Url.Action("Details", "KaniDB", new { id = item.KaniId }))'">
                            <td>
                                @item.Nimi "@item.Kutsumanimi"
                            </td>
                            <td>
                                @item.Rokotuspv.ToShortDateString()
                            </td>
                            <td>
                                @item.Syntymäpäivä.ToShortDateString()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>

    </dl>
}
@if (ViewBag.EiRokotettu != null)
{
    <dl class="row">
        <dt class="col-sm-2">
            Ei rokotettu
        </dt>
        <dd class="col-sm-10">
            <table class="table-sm table-hover">
                <thead>
                    <tr>
                        <th>
                            Nimi
                        </th>
                        <th>
                            Syntymäpäivä
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.EiRokotettu)
                    {
                        <tr onclick="location.href = '@(Url.Action("Details", "KaniDB", new { id = item.KaniId }))'">
                            <td>
                                @item.Nimi "@item.Kutsumanimi"
                            </td>
                            <td>
                                @item.Syntymäpäivä.ToShortDateString()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>
    </dl>
}